server:
  port: 8082
spring:
  application:
    name: vidasalud-ms-catalog
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.zcmgjhgjvtlceacwjuvv
    password: VidaSalud1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true